# netlify.toml
[build]
  command = "npm run build"
  publish = "dist"

# Redirect all routes to index.html (for React Router SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optional: Force proper MIME type for JS modules (usually not needed)
[[headers]]
  for = "/assets/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
